### ISSUE TITLE
refactor routes

### ISSUE THREAD

**Issue by darioaschero** [Badgegate/website#9]
- move `opportunities/[id]` and `summit` inside the` app/app` folder
- create a layout for ` app/app` this is where we should include the navbar avoiding to do it in each pages
- probably also the context should be here since we do not need it in the marketing landing page

**Comment by KishoreVB70** [comment]
I wanted to clarify one aspect before proceeding. Moving `opportunities` inside the `app/app` directory will result in the opportunity URL changing to `/app/opportunity` rather than the current URL path `/opportunity`. Could you confirm if this URL structure is acceptable for you.

Thank you

**Comment by darioaschero** [comment]
yes we move everything that is part of the app there, this was suggested by yannick. i think makes sense to have this segment, in order to share the same layout and reduce the re-rendering of the navbar (i guess)
https://nextjs.org/docs/app/building-your-application/routing#nested-routes
